---
- name: Déployer une application Docker avec Docker Compose
  hosts: gcp_vms
  become: yes # Toutes ces actions nécessitent les droits sudo

  tasks:
    # --- BLOC 1: Installation de Docker ---
    - name: 1. Installer les dépendances requises pour Docker
      apt:
        name: ['ca-certificates', 'curl', 'gnupg']
        state: latest
        update_cache: yes

    - name: 2. Ajouter la clé GPG officielle de Docker
      get_url:
        url: https://download.docker.com/linux/debian/gpg
        dest: /etc/apt/trusted.gpg.d/docker.gpg
        mode: '0644'
        force: yes

    - name: 3. Ajouter le dépôt Docker
      apt_repository:
        repo: "deb [arch=amd64 signed-by=/etc/apt/trusted.gpg.d/docker.gpg] https://download.docker.com/linux/debian bookworm stable"
        state: present

    - name: 4. Installer Docker Engine et Docker Compose
      apt:
        name: ['docker-ce', 'docker-ce-cli', 'containerd.io', 'docker-compose-plugin']
        state: latest

    # --- BLOC 2: Déploiement de l'application ---
    - name: 5. Créer un répertoire pour l'application sur les VM
      file:
        path: /app
        state: directory
        mode: '0755'

    - name: 6. Copier notre fichier docker-compose.yml
      copy:
        src: files/docker-compose.yml
        dest: /app/docker-compose.yml

    - name: 7. Lancer l'application avec Docker Compose
      command: docker compose up -d
      args:
        chdir: /app
